use errors::DriverError;
use model::asm::*;
use std::ffi::OsStr;
use std::fs::File;
use std::io::BufWriter;
use std::io::Write;

#[derive(PartialEq, Debug)]
pub enum Comments {
    Include,
    Exclude,
}

pub fn emit_code(asm: &Program, path: &OsStr, comments: Comments) -> Result<(), DriverError> {
    let file = File::options()
        .create(true)
        .write(true)
        .open(path)
        .map_err(|e| {
            DriverError::with_err_msg(&format!(
                "Failed to open {} for writing: {e}",
                path.display()
            ))
        })?;
    let mut writer = BufWriter::new(file);
    write_asm(&asm, &mut writer, comments)
}

const WARNING_HEADER: &[u8; 272] =
    br#"###################################################################
# WARNING! This assembly is generated by a toy compiler.          #
# Use at your own risk.                                           #
###################################################################
"#;

fn write_asm(prog: &Program, w: &mut impl Write, comments: Comments) -> Result<(), DriverError> {
    let func = &prog.func;

    if comments == Comments::Include {
        w.write_all(WARNING_HEADER)?;
    }

    // Page 19 of the book says function names should have an underscore prefix on macOS
    let fn_name_prefix = if cfg!(target_os = "macos") { "_" } else { "" };

    writeln!(w, "\t.globl {fn_name_prefix}{}", func.name)?;
    writeln!(w, "{fn_name_prefix}{}:", func.name)?;

    for instr in &func.instructions {
        write_instruction(instr, w)?;
    }

    // From page 19 of the book:
    // > This line enables an important security hardening measure: it indicates
    // > that your code doesn't need an executable stack. A region of memory is executable
    // > if the processor is permitted to execute machine instructions stored
    // > there. Making the stack non-executable is a basic defense against certain
    // > security exploits, but this defense can't be enabled for every program, because a
    // > few programs that use certain nonstandard language extensions actually need an executable
    // > stack. Including this line in an assembly file signals that it does not require
    // > an executable stack, which allows this security measure to be enabled. None
    // > of the code we generate in this book will require an executable stack, so
    // > we'll always emit this line.
    if cfg!(target_os = "linux") {
        if comments == Comments::Include {
            w.write_all(b"# This line prevents the stack from being executable.\n")?;
            w.write_all(b"# See page 19 of the book for more details.\n")?;
        }
        w.write_all(b".section .note.GNU-stack,\"\",@progbits\n")?;
    }

    Ok(())
}

fn write_instruction(instr: &Instruction, w: &mut impl Write) -> Result<(), DriverError> {
    use Instruction::*;

    write!(w, "\t")?;

    match instr {
        Mov { src, dst } => writeln!(w, "movl\t{src}, {dst}")?,
        Ret => writeln!(w, "ret")?,
    }

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_write_asm() {
        let prog = Program {
            func: Func {
                name: "main".to_string(),
                instructions: vec![
                    Instruction::Mov {
                        src: Operand::Imm(2),
                        dst: Operand::Register,
                    },
                    Instruction::Ret,
                ],
            },
        };
        let mut asm = Vec::new();
        write_asm(&prog, &mut asm, Comments::Exclude).unwrap();
        let asm = str::from_utf8(&asm).unwrap();
        assert_eq!(
            asm,
            "\t.globl main\nmain:\n\tmovl\t$2, %eax\n\tret\n.section .note.GNU-stack,\"\",@progbits\n"
        );
    }
}
